keys:
  - &nicole age1m2w4k4rgnzdynx0s9xqvx7k66dfa4jv5q20hgxp6dcjjwz09mdlqqzgves
  - &brad age1jrudgmztqp9n4th760e8t7nj3y7vyg3jn0j9khnxxe7g5lge945qrpd9uh

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *nicole
          - *brad
