{...}: {
  flake.modules.homeManager.wallust = {
    lib,
    pkgs,
    config,
    ...
  }: let
    # Fallback palette used until a wallpaper is applied, so waybar, kitty, and
    # neovim still get sane colors on a fresh machine with no wallpapers.
    palette = {
      background = "#1e1e2e";
      foreground = "#cdd6f4";
      color0 = "#45475a";
      color1 = "#f38ba8";
      color2 = "#a6e3a1";
      color3 = "#f9e2af";
      color4 = "#89b4fa";
      color5 = "#cba6f7";
      color6 = "#94e2d5";
      color7 = "#cdd6f4";
      color8 = "#6c7086";
      color9 = "#f38ba8";
      color10 = "#a6e3a1";
      color11 = "#f9e2af";
      color12 = "#89b4fa";
      color13 = "#cba6f7";
      color14 = "#94e2d5";
      color15 = "#f5e0dc";
    };

    mkDefineColors = c:
      builtins.concatStringsSep "\n" (
        map (i: "@define-color color${toString i} ${c."color${toString i}"};") (lib.range 0 15)
      );
    mkKittyColors = c:
      builtins.concatStringsSep "\n" (
        map (i: "color${toString i} ${c."color${toString i}"}") (lib.range 0 15)
      );
    mkLuaColors = c:
      builtins.concatStringsSep "\n" (
        map (i: "vim.g.terminal_color_${toString i}  = \"${c."color${toString i}"}\"") (lib.range 0 15)
      );
    mkVimColors = c:
      builtins.concatStringsSep "\n" (
        map (i: "let color${toString i}  = \"${c."color${toString i}"}\"") (lib.range 0 15)
      );

    fallback-waybar = pkgs.writeText "waybar-colors-fallback.css" ''
      @define-color bg ${palette.background};
      @define-color contrast ${palette.color0};
      @define-color lighter ${palette.color8};
      @define-color fg ${palette.foreground};
      @define-color cursorline ${palette.color1};
      @define-color comments ${palette.color8};
      @define-color cursor ${palette.color7};
      ${mkDefineColors palette}
    '';

    fallback-kitty = pkgs.writeText "colors-kitty-fallback.conf" ''
      foreground ${palette.foreground}
      background #000000
      cursor      ${palette.color6}
      ${mkKittyColors palette}
    '';

    fallback-neovim = pkgs.writeText "colors-neovim-fallback.lua" ''
      ${mkLuaColors palette}
    '';

    fallback-neopywal = pkgs.writeText "colors-neopywal-fallback.vim" ''
      let background = "${palette.background}"
      let foreground = "${palette.foreground}"
      let cursor     = "${palette.foreground}"
      ${mkVimColors palette}
    '';

    # Installs the fallback color files only when the real ones are absent, so
    # an existing theme (generated by wallust from a wallpaper) is never
    # clobbered.
    ensure-wallust-colors = pkgs.writeShellScriptBin "ensure-wallust-colors" ''
      cache_dir="$HOME/.cache/wallust"
      ${pkgs.coreutils}/bin/mkdir -p "$cache_dir"
      [ -f "$cache_dir/waybar-colors.css" ] || ${pkgs.coreutils}/bin/install -m 0644 "${fallback-waybar}" "$cache_dir/waybar-colors.css"
      [ -f "$cache_dir/colors-kitty.conf" ] || ${pkgs.coreutils}/bin/install -m 0644 "${fallback-kitty}" "$cache_dir/colors-kitty.conf"
      [ -f "$cache_dir/colors-neovim.lua" ] || ${pkgs.coreutils}/bin/install -m 0644 "${fallback-neovim}" "$cache_dir/colors-neovim.lua"
      [ -f "$cache_dir/colors_neopywal.vim" ] || ${pkgs.coreutils}/bin/install -m 0644 "${fallback-neopywal}" "$cache_dir/colors_neopywal.vim"
    '';

    # Sets a solid-color background so sway never ends up with no background
    # when no wallpaper images are available.
    set-solid-background = pkgs.writeShellScriptBin "set-solid-background" ''
      pkill swaybg || true
      ${pkgs.swaybg}/bin/swaybg -c "${palette.background}" &
    '';

    random-wallpaper = pkgs.writeShellScriptBin "random-wallpaper" ''
      dir="$HOME/Pictures/wallpapers"
      wallpaper=$(ls "$dir"/*.{jpg,jpeg,png,gif,webp} 2>/dev/null | shuf -n 1)
      if [ -z "$wallpaper" ]; then
        echo "No wallpapers found in $dir; using fallback solid background"
        ${set-solid-background}/bin/set-solid-background
        ${ensure-wallust-colors}/bin/ensure-wallust-colors
        exit 0
      fi
      switch-wallpaper "$wallpaper"
    '';

    switch-wallpaper = pkgs.writeShellScriptBin "switch-wallpaper" ''
      wallpaper="$1"
      if [ -z "$wallpaper" ] || [ ! -f "$wallpaper" ]; then
        echo "Wallpaper not found: $wallpaper" >&2
        ${set-solid-background}/bin/set-solid-background
        ${ensure-wallust-colors}/bin/ensure-wallust-colors
        exit 0
      fi

      # Generate color scheme and render templates.
      ${pkgs.wallust}/bin/wallust run -s "$wallpaper" || true
      ${ensure-wallust-colors}/bin/ensure-wallust-colors

      # Swap wallpaper
      pkill swaybg || true
      ${pkgs.swaybg}/bin/swaybg -i "$wallpaper" -m fill &

      # Reload waybar CSS
      pkill -SIGUSR2 waybar || true

      # Hot-reload kitty colors in every running kitty instance.
      for socket in /tmp/kitty-socket-*; do
        kitty @ --to "unix:$socket" set-colors --all --configured \
          ~/.cache/wallust/colors-kitty.conf 2>/dev/null || true
      done

      # Safety net: force background to black in the current window.
      printf '\033]11;#000000\007'
    '';
  in {
    options.limonene.wallust = {
      ensureColorsBin = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Path to the script that installs fallback wallust colors when missing";
      };
      setSolidBackgroundBin = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Path to the script that sets a solid fallback sway background";
      };
    };

    config = {
      limonene.wallust = {
        ensureColorsBin = "${ensure-wallust-colors}/bin/ensure-wallust-colors";
        setSolidBackgroundBin = "${set-solid-background}/bin/set-solid-background";
      };

      home.packages = [
        pkgs.wallust
        switch-wallpaper
        random-wallpaper
        ensure-wallust-colors
        set-solid-background
      ];

      xdg.configFile."wallust/wallust.toml".text = ''
        palette = "harddark16"
        check_contrast = true

        [templates]
        waybar.template = "waybar-colors.css"
        waybar.target = "~/.cache/wallust/waybar-colors.css"
        waybar.pywal = true

        kitty.template = "colors-kitty.conf"
        kitty.target = "~/.cache/wallust/colors-kitty.conf"
        kitty.pywal = true

        neovim.template = "colors-neovim.lua"
        neovim.target = "~/.cache/wallust/colors-neovim.lua"
        neovim.pywal = true

        neopywal.template = "colors_neopywal.vim"
        neopywal.target = "~/.cache/wallust/colors_neopywal.vim"
        neopywal.pywal = true
      '';

      xdg.configFile."wallust/templates/waybar-colors.css".text = ''
        @define-color bg {background};
        @define-color contrast {color0};
        @define-color lighter {color8};
        @define-color fg {foreground};
        @define-color cursorline {color1};
        @define-color comments {color8};
        @define-color cursor {color7};
        @define-color color0 {color0};
        @define-color color1 {color1};
        @define-color color2 {color2};
        @define-color color3 {color3};
        @define-color color4 {color4};
        @define-color color5 {color5};
        @define-color color6 {color6};
        @define-color color7 {color7};
        @define-color color8 {color8};
        @define-color color9 {color9};
        @define-color color10 {color10};
        @define-color color11 {color11};
        @define-color color12 {color12};
        @define-color color13 {color13};
        @define-color color14 {color14};
        @define-color color15 {color15};
      '';

      xdg.configFile."wallust/templates/colors_neopywal.vim".text = ''
        let background = "{background}"
        let foreground = "{foreground}"
        let cursor     = "{foreground}"
        let color0  = "{color0}"
        let color1  = "{color1}"
        let color2  = "{color2}"
        let color3  = "{color3}"
        let color4  = "{color4}"
        let color5  = "{color5}"
        let color6  = "{color6}"
        let color7  = "{color7}"
        let color8  = "{color8}"
        let color9  = "{color9}"
        let color10 = "{color10}"
        let color11 = "{color11}"
        let color12 = "{color12}"
        let color13 = "{color13}"
        let color14 = "{color14}"
        let color15 = "{color15}"
      '';

      xdg.configFile."wallust/templates/colors-neovim.lua".text = ''
        vim.g.terminal_color_0  = "{color0}"
        vim.g.terminal_color_1  = "{color1}"
        vim.g.terminal_color_2  = "{color2}"
        vim.g.terminal_color_3  = "{color3}"
        vim.g.terminal_color_4  = "{color4}"
        vim.g.terminal_color_5  = "{color5}"
        vim.g.terminal_color_6  = "{color6}"
        vim.g.terminal_color_7  = "{color7}"
        vim.g.terminal_color_8  = "{color8}"
        vim.g.terminal_color_9  = "{color9}"
        vim.g.terminal_color_10 = "{color10}"
        vim.g.terminal_color_11 = "{color11}"
        vim.g.terminal_color_12 = "{color12}"
        vim.g.terminal_color_13 = "{color13}"
        vim.g.terminal_color_14 = "{color14}"
        vim.g.terminal_color_15 = "{color15}"
      '';

      xdg.configFile."wallust/templates/colors-kitty.conf".text = ''
        foreground {foreground}
        background #000000
        cursor      {color6}
        color0  {color0}
        color1  {color1}
        color2  {color2}
        color3  {color3}
        color4  {color4}
        color5  {color5}
        color6  {color6}
        color7  {color7}
        color8  {color8}
        color9  {color9}
        color10 {color10}
        color11 {color11}
        color12 {color12}
        color13 {color13}
        color14 {color14}
        color15 {color15}
      '';
    };
  };
}
