# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  # Script invoked by udev to flip the ACPI platform profile. Referenced by
  # its store path so the udev rules build step can verify it exists.
  platformProfileSwitch = pkgs.writeShellScriptBin "platform-profile" ''
    echo "$1" > /sys/firmware/acpi/platform_profile
  '';
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  # Save da pooower
  services.power-profiles-daemon.enable = true;
  services.udev.extraRules = ''
    # Switch to low-power ACPI profile on battery (mains adapter only, to
    # avoid spurious triggers from USB-C port power supplies)
    SUBSYSTEM=="power_supply", ATTR{type}=="Mains", ATTR{online}=="0", RUN+="${platformProfileSwitch}/bin/platform-profile low-power"
    SUBSYSTEM=="power_supply", ATTR{type}=="Mains", ATTR{online}=="1", RUN+="${platformProfileSwitch}/bin/platform-profile balanced"
  '';

  fileSystems."/" = {
    device = "/dev/mapper/luks-6407451f-e577-46ef-92c9-10433024d9f1";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-6407451f-e577-46ef-92c9-10433024d9f1".device = "/dev/disk/by-uuid/6407451f-e577-46ef-92c9-10433024d9f1";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-6407451f-e577-46ef-92c9-10433024d9f1";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-6407451f-e577-46ef-92c9-10433024d9f1";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4B93-DBAD";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-099e44df-0372-4808-bf9a-74f2dba56f71";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
