# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-97195717-b79a-41dd-9418-29de7dad5e90";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-97195717-b79a-41dd-9418-29de7dad5e90".device = "/dev/disk/by-uuid/97195717-b79a-41dd-9418-29de7dad5e90";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20BD-CD9F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-e4c4f4e3-e6c7-43f2-8a41-5bc7add2a577"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

